---
title: "第一次作业"
output: html_document
---

8.(a)
```{r}
college = read.csv("C:/Users/15522/Desktop/College.csv",header = T)
```


(b)
```{r}
rownames(college) = college[, 1]
fix(college)
```

```{r}
college = college[, -1]
fix(college)
```



(c)i
```{r}
summary(college)
```

ii
```{r}
college[,1]=as.factor(college[,1])
pairs(college[,1:10])
```

iii
```{r}
plot(college$Private,college$Outstate)
```

iv
```{r}
Elite = rep ("No", nrow (college)) 
Elite[college$Top10perc > 50] = "Yes" 
Elite = as.factor (Elite) 
college = data.frame (college , Elite)
```

```{r}
summary(college$Elite)
```

```{r}
plot(college$Elite,college$Outstate)
```



9.(a)
```{r}
Auto = read.csv("C:/Users/15522/Desktop/Auto.csv",header=T,na.strings="?")
Auto = na.omit(Auto)
summary(Auto)
```


(b)
```{r}
range(Auto$mpg)
```

```{r}
range(Auto$cylinders)
```

```{r}
range(Auto$displacement)
```

```{r}
range(Auto$horsepower)
```

```{r}
range(Auto$weight)
```

```{r}
range(Auto$acceleration)
```



(c)
```{r}
mean(Auto$mpg)
sd(Auto$mpg)
```

```{r}
mean(Auto$cylinders)
sd(Auto$cylinders)
```

```{r}
mean(Auto$displacement)
sd(Auto$displacement)
```

```{r}
mean(Auto$horsepower)
sd(Auto$horsepower)
```

```{r}
mean(Auto$weight)
sd(Auto$weight)
```

```{r}
mean(Auto$acceleration)
sd(Auto$acceleration)
```


(d)
```{r}
auto=Auto[-c(10,85),]
dim(auto)
```

```{r}
range(auto$mpg)
mean(auto$mpg)
sd(auto$mpg)
```

```{r}
range(auto$cylinders)
mean(auto$cylinders)
sd(auto$cylinders)
```

```{r}
range(auto$displacement)
mean(auto$displacement)
sd(auto$displacement)
```

```{r}
range(auto$horsepower)
mean(auto$horsepower)
sd(auto$horsepower)
```

```{r}
range(auto$weight)
mean(auto$weight)
sd(auto$weight)
```

```{r}
range(auto$acceleration)
mean(auto$acceleration)
sd(auto$acceleration)
```
