---
title: "第三次作业"
output: html_document
---


6(a)
```{r}
set.seed(1)
library(ISLR2)
summary(Default)
```
 
 
```{r}
attach(Default)
glm.fit<-glm(default~balance+income,data=Default,family=binomial)
```
 
 


(b)
```{r}
train=sample(dim(Default)[1],dim(Default)[1]/2)
glm.fit=glm(default~income+balance,family = binomial,data = Default,subset = train)
glm.pred=rep('No',dim(Default)[1]/2)
glm.probs=predict(glm.fit,Default[-train,],type='response')
glm.pred[glm.probs>0.5]='Yes'
mean(glm.pred!=Default[-train,]$default)
```
 


(c)
```{r}
train=sample(dim(Default)[1],dim(Default)[1]/2)
glm.fit=glm(default~income+balance,family = binomial,data = Default,subset = train)
glm.pred=rep('No',dim(Default)[1]/2)
glm.probs=predict(glm.fit,Default[-train,],type='response')
glm.pred[glm.probs>0.5]='Yes'
mean(glm.pred!=Default[-train,]$default)
```


```{r}
train=sample(dim(Default)[1],dim(Default)[1]/2)
glm.fit=glm(default~income+balance,family = binomial,data = Default,subset = train)
glm.pred=rep('No',dim(Default)[1]/2)
glm.probs=predict(glm.fit,Default[-train,],type='response')
glm.pred[glm.probs>0.5]='Yes'
mean(glm.pred!=Default[-train,]$default)
```


```{r}
train=sample(dim(Default)[1],dim(Default)[1]/2)
glm.fit=glm(default~income+balance,family = binomial,data = Default,subset = train)
glm.pred=rep('No',dim(Default)[1]/2)
glm.probs=predict(glm.fit,Default[-train,],type='response')
glm.pred[glm.probs>0.5]='Yes'
mean(glm.pred!=Default[-train,]$default)
```




(d)
```{r}
train=sample(dim(Default)[1],dim(Default)[1]/2)
glm.fit=glm(default~income+balance+student,family = binomial,data = Default,subset = train)
glm.pred=rep('No',dim(Default)[1]/2)
glm.probs=predict(glm.fit,Default[-train,],type='response')
glm.pred[glm.probs>0.5]='Yes'
mean(glm.pred!=Default[-train,]$default)
```

 
 


7(a)
```{r}
glm.fit=glm(default~income+balance,family = binomial,data = Default)
summary(glm.fit)
```
 
 


(b)
```{r}
boot.fn=function(data,index){return((coef(glm(default~income+balance,family = binomial,data = Default,subset = index))))}
```
 
 


(c)
```{r}
library(boot)
boot(Default,boot.fn,1000)
```
 
 


8(a)
```{r}
x=rnorm(100)
e=rnorm(100)
```
 
 


(b)
```{r}
y=1+2*x+3*x^2+4*x^3+e
```
 


(c)
```{r}
library(leaps)
library(MASS)
df=data.frame(x,x^2,x^3,x^4,x^5,x^6,x^7,x^8,x^9,x^10)
regfit.full=regsubsets(y~.,data=df,nvmax=10)
reg.summary=summary(regfit.full)
```

```{r}
reg.summary$cp
```

```{r}
reg.summary$bic
```
 
```{r}
reg.summary$adjr2
```
 



```{r}
par(mfrow=c(2,2))
plot(reg.summary$cp,xlab = "Number of variables",ylab = "Cp")
points(which.min(reg.summary$cp),reg.summary$cp[which.min(reg.summary$cp)],col="blue",pch=20)
plot(reg.summary$bic,xlab = "Number of variables",ylab = "BIC")
points(which.min(reg.summary$bic),reg.summary$bic[which.min(reg.summary$bic)],col="blue",pch=20)
plot(reg.summary$adjr2,xlab = "Number of variables",ylab = "Adjusted RSq")
points(which.max(reg.summary$adjr2),reg.summary$adjr2[which.max(reg.summary$adjr2)],col="blue",pch=20)
```
 


(d)
```{r}
regfit.fwd=regsubsets(y~.,data=df,nvmax=10,method = 'forward')
regfwd.summary=summary(regfit.fwd)
regfwd.summary
```
 
```{r}
regfwd.summary$cp
```
 
```{r}
regfwd.summary$bic
```
 
```{r}
regfwd.summary$adjr2
```
 



```{r}
regfit.bwd=regsubsets(y~.,data=df,nvmax=10,method = 'backward')
regbwd.summary=summary(regfit.bwd)
regbwd.summary
```
 
```{r}
regbwd.summary$cp
```
 
```{r}
regbwd.summary$bic
```
 
```{r}
regbwd.summary$adjr2
```





(e)
```{r}
library(glmnet)
x=model.matrix(y~.,df)[,-1]
y=y
train=sample(1:100,50)
test=(-train)
y.test=y[test]
```
 
```{r}
cv.out=cv.glmnet(x[train,],y[train],alpha=1)
plot(cv.out)
```
 
```{r}
bestlam=cv.out$lambda.min
show(bestlam)
```
 



```{r}
lasso=glmnet(x,y,alpha=1)
lasso.coef=predict(lasso,type="coefficients",s=bestlam)
show(lasso.coef)
```





(f)
```{r}
z=1+7*x^7+e
df2=data.frame(x,x^2,x^3,x^4,x^5,x^6,x^7,x^8,x^9,x^10,z)
regfit.full=regsubsets(y~.,data=df2,nvmax=10)
reg.summary=summary(regfit.full)
reg.summary
```

```{r}
reg.summary$cp
```
 
```{r}
reg.summary$bic
```
 
```{r}
reg.summary$adjr2
```

```{r}
x2=model.matrix(z~.,df2)[,-1]
y2=z
y2.test=y2[test]
cv.out2=cv.glmnet(x2[train,],y2[train],alpha=1)
bestlam2=cv.out2$lambda.min
show(bestlam2)
```
 



```{r}
lasso2=glmnet(x2,y2,alpha=1)
lasso.coef2=predict(lasso2,type="coefficients",s=bestlam2)
show(lasso.coef2)
```
 


9(a)
```{r}
library(ISLR)
attach(College)
summary(College)
```
 
```{r}
set.seed(1)
train=sample(nrow(College),nrow(College)/2)
test=(-train)
college.train=College[train,-1]
college.test=College[test,-1]
```
 


(b)
```{r}
lm.fit=lm(Apps~.,data=college.train)
lm.pred=predict(lm.fit,college.test,type="response")
MSE=mean((lm.pred-college.test$Apps)^2)
MSE
```
 


(c)
```{r}
X=model.matrix(Apps~.,college.train)[,-1]
Y=college.train$Apps
Xt=model.matrix(Apps~.,college.test)[,-1]
cv.out=cv.glmnet(X,Y,alpha=0)
plot(cv.out)
```
 
```{r}
bestlam=cv.out$lambda.min
ridge.mod=glmnet(X,Y,alpha=0)
ridge.pred=predict(ridge.mod,s=bestlam,newx=Xt)
MSE=mean((ridge.pred-college.test$Apps)^2)
MSE
```
 


(d)
```{r}
cv.out=cv.glmnet(X,Y,alpha=1)
plot(cv.out)
```
 
```{r}
bestlam=cv.out$lambda.min
lasso.mod=glmnet(X,Y,alpha=1)
lasso.pred=predict(lasso.mod,s=bestlam,newx=Xt)
MSE=mean((lasso.pred-college.test$Apps)^2)
MSE
```

```{r}
lasso.coef=predict(lasso.mod,type="coefficients",s=bestlam)
lasso.coef
```
 



